---
title: "R Notebook"
output: html_notebook
---

# Import dependencies

```{r}
library(tidyverse)
library(here)
library(ggthemes)
library(tidyboot)
library(ggh4x)
```


```{r}
colorblind_pal()(8)
```
"#E69F00","#D55E00","#56B4E9","#009E73","#000000"

# fine-grained analyses

```{r,message=FALSE}
d.zindiv.raw <- read_csv(here('results/combined_effect_ave_all/combined_effect_ave_z_rep_albert-xxlarge-v2.csv'))
d.qry.raw <- read_csv(here('results/combined_effect_ave_all/combined_effect_ave_query_albert-xxlarge-v2.csv'))
d.key.raw <- read_csv(here('results/combined_effect_ave_all/combined_effect_ave_key_albert-xxlarge-v2.csv'))
d.val.raw <- read_csv(here('results/combined_effect_ave_all/combined_effect_ave_value_albert-xxlarge-v2.csv'))
#d.att <- read_csv(here('results/combined_effect_ave_all/combined_effect_ave_attention_albert-xxlarge-v2.csv'))
#d.qnk <- read_csv(here('results/combined_effect_ave_all/combined_effect_ave_q_and_k_albert-xxlarge-v2.csv'))
```

```{r}
sent_list <- d.zindiv.raw %>%
  filter((layer_id==0)&(head_id==0)&(pos_type=='context')) %>%
  separate(pair_id, into = c('prefix', 'pair_id')) %>%
  select(c("pair_id","original_score","cue_type")) %>%
  pivot_wider(names_from="cue_type",values_from="original_score") %>%
  mutate(group_score=str_c(context,verb,sep="-")) %>%
  filter(group_score=="TRUE-TRUE") %>%
  pull("pair_id")
```

```{r}
d.zindiv <- d.zindiv.raw %>%
  separate(pair_id, into = c('prefix', 'pair_id')) %>%
  filter(pair_id %in% sent_list) %>%
  mutate(layer_id=layer_id+1) %>%
  mutate(head_id=head_id+1)

d.qry <- d.qry.raw %>%
  separate(pair_id, into = c('prefix', 'pair_id')) %>%
  filter(pair_id %in% sent_list) %>%
  mutate(layer_id=layer_id+1) %>%
  mutate(head_id=head_id+1)

d.key <- d.key.raw %>%
  separate(pair_id, into = c('prefix', 'pair_id')) %>%
  filter(pair_id %in% sent_list) %>%
  mutate(layer_id=layer_id+1) %>%
  mutate(head_id=head_id+1)

d.val <- d.val.raw %>%
  separate(pair_id, into = c('prefix', 'pair_id')) %>%
  filter(pair_id %in% sent_list) %>%
  mutate(layer_id=layer_id+1) %>%
  mutate(head_id=head_id+1)

#d.attqnk <- bind_rows(d.att,d.qnk) %>%
#  filter(original_score) %>%
#  filter(pos_type%in%c('all','masks-options','options-masks','rest-options','rest-masks',
#                       'options-rest','masks-rest','context-rest','verb-rest')) %>%
#  mutate(pos_type = replace(pos_type,pos_type=='all','attention')) %>%
  #mutate(pos_type = replace(pos_type,pos_type=="masks-options","query@options\n& key@masks")) %>%
  #mutate(pos_type = replace(pos_type,pos_type=="options-masks","query@masks\n& key@options")) %>%
  #mutate(pos_type=factor(pos_type,levels=c('attention','masks-options','options-masks','rest-options','rest-masks',
  #                                         'options-rest','masks-rest','context-rest','verb-rest'))) %>%
#  mutate(layer_id=layer_id+1) %>%
#  mutate(head_id=head_id+1)

```

```{r}
d.zindiv %>% pull(cue_type) %>% unique()
d.zindiv %>% pull(pos_type) %>% unique()
d.qry %>% pull(cue_type) %>% unique()
d.qry %>% pull(pos_type) %>% unique()
d.key %>% pull(cue_type) %>% unique()
d.key %>% pull(pos_type) %>% unique()
d.val %>% pull(cue_type) %>% unique()
d.val %>% pull(pos_type) %>% unique()
#d.att %>% pull(cue_type) %>% unique()
#d.att %>% pull(pos_type) %>% unique()
#d.qnk %>% pull(cue_type) %>% unique()
#d.qnk %>% pull(pos_type) %>% unique()
#d.attqnk %>% pull(cue_type) %>% unique()
#d.attqnk %>% pull(pos_type) %>% unique()
```

# See how many heads are involved in this circuit
```{r}
p_threshold <- 0.05
head_list <- d.zindiv %>%
  filter(cue_type=="context") %>%
  group_by(layer_id, head_id, pos_type) %>%
  summarize(p.val = t.test(effect_ave)$p.value,
            t.val = t.test(effect_ave)$statistic) %>%
  mutate(p.log=(-log10(p.val))) %>%
  mutate(cut_off=-log10(p_threshold/12/64/7/2)) %>%
  filter(p.log>cut_off) %>%
  pull(head_id) %>% unique()
length(head_list)
```

```{r}
pos_type_list <- c('context','verb','options','masks','rest')
d.headall <- bind_rows(d.zindiv %>% 
                        filter(pos_type%in%pos_type_list) %>%
                        mutate(pos_type=factor(pos_type,levels=pos_type_list)) %>%
                        mutate(rep_type='transformation'),
                       d.qry %>%
                         filter(pos_type%in%pos_type_list) %>%
                         mutate(pos_type=factor(pos_type,levels=pos_type_list)),
                       d.key %>%
                         filter(pos_type%in%pos_type_list) %>%
                         mutate(pos_type=factor(pos_type,levels=pos_type_list)),
                       d.val %>%
                         filter(pos_type%in%pos_type_list) %>%
                         mutate(pos_type=factor(pos_type,levels=pos_type_list))
                        )
d.headall %>% head()
```

# Bootstrap (takes time)
```{r}
d.head_all.boot <- d.headall %>%
  group_by(cue_type,layer_id,head_id,rep_type,pos_type) %>%
  tidyboot_mean(effect_ave, nboot = 10) %>%
  rename(y=empirical_stat)
write.csv(d.head_all.boot,file="headall_boot.csv",row.names=FALSE)
```

```{r}
d.head_all.boot <- read_csv("headall_boot.csv")
d.head_all.boot %>% head()
```

```{r}
#p_threshold <- 0.001
bar_center <- -0.01
bar_height <- 0.015
t.vals.all <- d.headall %>%
  group_by(cue_type, layer_id, head_id, rep_type, pos_type) %>%
  summarize(p.val = t.test(effect_ave)$p.value,
            t.val = t.test(effect_ave)$statistic) %>%
  mutate(p.log=(-log10(p.val))) %>%
  #mutate(cut_off=-log10(p_threshold/12/64/7/2)) %>%
  #mutate(y = NA) %>%
  #mutate(y = replace(y,(p.log>cut_off)&(t.val>0)&(pos_type=="context"),bar_center-4*bar_height)) %>%
  #mutate(y = replace(y,(p.log>cut_off)&(t.val>0)&(pos_type=="verb"),bar_center-3*bar_height)) %>%
  #mutate(y = replace(y,(p.log>cut_off)&(t.val>0)&(pos_type=="options"),bar_center-2*bar_height)) %>%
  #mutate(y = replace(y,(p.log>cut_off)&(t.val>0)&(pos_type=="masks"),bar_center-bar_height)) %>%
  #mutate(y = replace(y,(p.log>cut_off)&(t.val>0)&(pos_type=="rest"),bar_center)) %>%
  mutate(y = 0) %>%
  mutate(y = replace(y,pos_type==pos_type_list[1],bar_center-4*bar_height)) %>%
  mutate(y = replace(y,pos_type==pos_type_list[2],bar_center-3*bar_height)) %>%
  mutate(y = replace(y,pos_type==pos_type_list[3],bar_center-2*bar_height)) %>%
  mutate(y = replace(y,pos_type==pos_type_list[4],bar_center-bar_height)) %>%
  mutate(y = replace(y,pos_type==pos_type_list[5],bar_center)) %>%
  mutate(alpha = 0) %>%
  mutate(alpha = replace(alpha,p.log>-log10(0.05/12/64/7/2),0.4)) %>%
  mutate(alpha = replace(alpha,p.log>-log10(0.01/12/64/7/2),0.6)) %>%
  mutate(alpha = replace(alpha,p.log>-log10(0.005/12/64/7/2),0.8)) %>%
  mutate(alpha = replace(alpha,p.log>-log10(0.001/12/64/7/2),1.0)) %>%
  select(cue_type,layer_id,head_id,rep_type,pos_type,y,alpha,p.val)
write.csv(t.vals.all,file="tvals_all.csv",row.names=FALSE)
```

```{r}
t.vals.all <- read_csv("tvals_all.csv")
t.vals.all %>% head()
```

```{r}
d.headall.plot <- bind_rows(d.head_all.boot %>% 
                              select(cue_type,layer_id,head_id,rep_type,pos_type,y,ci_lower,ci_upper) %>%
                              mutate(plot_type='line'),
                            t.vals.all %>%
                              mutate(plot_type='tile'))
```

```{r}
for (plot_head_id in 1:64) {
#for (plot_head_id in c(3,8,11,16,17,21,23,24,26,28,29,35,37,40,42,45,46,48,50,51,53,55,56,58,60)) {
for (plot_cue_type in c("context","verb")) {
d.head <- d.headall.plot %>% 
  filter(cue_type==plot_cue_type) %>%
  filter(head_id==plot_head_id) %>%
  mutate(rep_type=factor(rep_type,levels=c('transformation','query','key','value'))) %>%
  mutate(plot_type=factor(plot_type,levels=c('tile','line'))) %>%
  mutate(pos_type=factor(pos_type,levels=pos_type_list))

d.head %>%
  ggplot(aes(x=as.factor(layer_id), y=y, group=pos_type)) +
  geom_hline(yintercept=0) +
  geom_tile(data = subset(d.head, plot_type == 'tile'),
            height=bar_height,width=1,
            #aes(alpha=alpha,color="white",fill=pos_type)) +
            aes(alpha=alpha,fill=pos_type)) +
  geom_line(data = subset(d.head, plot_type == 'line'),
            aes(color=pos_type),
            linewidth=1.2,position=position_dodge(width=0.5)) +
  geom_errorbar(data = subset(d.head, plot_type == 'line'),
                aes(ymin=ci_lower, ymax=ci_upper, color=pos_type), 
                width=0.8,size=0.8,linetype='solid',position=position_dodge(width=0.5)) +
  theme_few() +
  scale_color_manual(values=c("#E69F00","#D55E00","#56B4E9","#009E73","#000000")) +
  scale_fill_manual(values=c("#E69F00","#D55E00","#56B4E9","#009E73","#000000")) +
  scale_alpha(limits = c(0.0, 1.0)) +
  ylim(-0.08,NA) + 
  labs(x = 'Layer', y ='Effect') +
  guides(color=FALSE,alpha=FALSE,fill=guide_legend(ncol=5,order=1)) +
  facet_grid(plot_type~rep_type,scales = "free_y") +
  force_panelsizes(rows = c(unit(0.6,"in"), unit(3.0,"in")),
                   cols = c(unit(2.5,"in"), unit(2.5,"in"),unit(2.5,"in"), unit(2.5,"in"))) +
  theme(legend.position = 'top', legend.title = element_blank(), legend.box="vertical",
        axis.text.x=element_text(size=10), axis.text.y=element_text(size=14), axis.title=element_text(size=18),
        strip.text.x=element_text(size=16), legend.text=element_text(size=16), strip.text.y=element_blank(),
        axis.line = element_line(colour = "black"),
        panel.border = element_blank(),panel.background = element_blank())
#library(grid)
#library(gtable)
#gt = ggplot_gtable(ggplot_build(g))
#gtable_show_layout(gt)
ggsave(paste('headwise/all/alpha/head_',plot_head_id,'_',plot_cue_type,'.pdf',sep=""), units = 'in', width = 10, height = 3.6)
}}
```

```{r}
show_cue_type <- "context"
show_head_id <- 44
show_pos_type <- "context"
show_rep_type <- "key"
t.vals.all %>% filter((cue_type==show_cue_type)&(head_id==show_head_id)&(pos_type==show_pos_type)&(rep_type==show_rep_type))
```

```{r}
show_cue_type <- "context"
show_head_id <- 44
show_pos_type <- "context"
show_rep_type <- "key"
d.head_all.boot %>% filter((cue_type==show_cue_type)&(head_id==show_head_id)&(pos_type==show_pos_type)&(rep_type==show_rep_type))
```

```{r}
library(gridExtra)
grid.arrange(
  ggplot(data = t.vals.all %>% 
           filter(cue_type==plot_cue_type) %>%
           filter(head_id==plot_head_id) %>%
           mutate(rep_type=factor(rep_type,levels=c('transformation','query','key','value'))) %>%
           mutate(pos_type=factor(pos_type,levels=c("context","verb","options","masks","rest"))), 
         aes(x = as.factor(layer_id), y = y, fill = pos_type, group = pos_type)) +
    geom_tile() + xlab(NULL) + ylab(NULL) + 
    facet_grid( ~ rep_type) +
    theme_few() +
    scale_fill_manual(values=c("#E69F00","#D55E00","#56B4E9","#009E73","#000000")) +
    force_panelsizes(rows = c(0.1)) +
    theme(aspect.ratio = 0.1, legend.position = 'top', legend.title = element_blank(),
        axis.text.x=element_blank(),axis.text.y=element_blank(),
        axis.ticks.x=element_blank(),axis.ticks.y=element_blank(),
        panel.border = element_blank()),
  ggplot(data = d.head_all.boot %>% 
           select(cue_type,layer_id,head_id,rep_type,pos_type,y,ci_lower,ci_upper) %>% 
           filter(cue_type==plot_cue_type) %>%
           filter(head_id==plot_head_id) %>%
           mutate(rep_type=factor(rep_type,levels=c('transformation','query','key','value'))) %>%
           mutate(pos_type=factor(pos_type,levels=c("context","verb","options","masks","rest"))), 
         aes(x = layer_id, y = y),color = pos_type, group = pos_type) +
    geom_line() +
    facet_grid( ~ rep_type) + 
    geom_hline(yintercept=0) +
    geom_line(size=1.2,position = position_dodge(width = 0.3)) +
    geom_errorbar(aes(ymin=ci_lower, ymax=ci_upper), width=0.8,size=0.8,linetype='solid',position = position_dodge(width = 0.3)) +
    theme_few() +
    scale_color_manual(values=c("#E69F00","#D55E00","#56B4E9","#009E73","#000000")) +
    force_panelsizes(rows = c(1.0)) +
    labs(x = 'Layer', y ='Effect') +
    guides(color=guide_legend(ncol=5)) +
    theme(aspect.ratio = 1,legend.position = 'top', legend.title = element_blank(),
        axis.text.x=element_text(size=10),axis.text.y=element_text(size=14), axis.title=element_blank(),
        strip.text=element_text(size=16), legend.text=element_text(size=16)) ,
  nrow=2)
ggsave(paste('headwise/all/head_',plot_head_id,'_',plot_cue_type,'.pdf',sep=""), units = 'in', width = 8, height = 3)
```

# 1.4.1: z rep
```{r}
d.zindiv %>% pull(cue_type) %>% unique()
d.zindiv %>% pull(pos_type) %>% unique()
d.zindiv %>% pull(layer_id) %>% unique()
d.zindiv %>% pull(head_id) %>% unique()
d.zindiv %>% filter(cue_type=="verb") %>% pull(pair_id) %>% unique()
```

```{r}
for (plot_cue_type in c("context","verb")) {
d.zindiv %>%
  filter(cue_type==plot_cue_type) %>%
  group_by(head_id, layer_id, pos_type) %>%
  tidyboot_mean(effect_ave, nboot = 10) %>%
  ggplot(aes(x = as.factor(layer_id), y = empirical_stat, color = pos_type, group = pos_type)) +
    geom_hline(yintercept=0) +
    geom_line(size=0.8,position = position_dodge(width = 0.3)) +
    geom_errorbar(aes(ymin=ci_lower, ymax=ci_upper), width=0.5,size=0.5,linetype='solid',position = position_dodge(width = 0.3)) +
    scale_color_manual(values=c("#E69F00","#D55E00","#56B4E9","#009E73","#000000","#0072B2","#CC79A7")) +
    #"#000000" "#E69F00" "#56B4E9" "#009E73" "#F0E442" "#0072B2" "#D55E00" "#CC79A7"
    facet_wrap( ~ head_id) +
    theme_few() +
    labs(x = 'Layer', y ='Effect') +
    theme(aspect.ratio = 1,legend.position = 'top', legend.title = element_blank(), 
          axis.text.x=element_text(size=7),axis.text.y=element_text(size=10), axis.title=element_text(size=16),
          strip.text=element_text(size=10), legend.text=element_text(size=16)) +
ggsave(paste('zrep_all_',plot_cue_type,'.pdf',sep=""), units = 'in', width = 16, height = 16)
}
```

```{r}
p_threshold <- 0.01
bar_center <- 2.5
bar_height <- 0.2
t.vals.zrep <- d.zindiv %>%
  group_by(cue_type, layer_id, head_id, pos_type) %>%
  summarize(p.val = t.test(effect_ave)$p.value,
            t.val = t.test(effect_ave)$statistic) %>%
  mutate(p.log=(-log10(p.val))) %>%
  mutate(cut_off=-log10(p_threshold/12/64/7/2)) %>%
  mutate(y = NA) %>%
  mutate(y = replace(y,(p.log>cut_off)&(t.val>0)&(pos_type=="context"),bar_center-3*bar_height)) %>%
  mutate(y = replace(y,(p.log>cut_off)&(t.val>0)&(pos_type=="verb"),bar_center-2*bar_height)) %>%
  mutate(y = replace(y,(p.log>cut_off)&(t.val>0)&(pos_type=="options"),bar_center-bar_height)) %>%
  mutate(y = replace(y,(p.log>cut_off)&(t.val>0)&(pos_type=="masks"),bar_center)) %>%
  mutate(y = replace(y,(p.log>cut_off)&(t.val>0)&(pos_type=="rest"),bar_center+bar_height)) %>%
  mutate(y = replace(y,(p.log>cut_off)&(t.val>0)&(pos_type=="period"),bar_center+2*bar_height)) %>%
  mutate(y = replace(y,(p.log>cut_off)&(t.val>0)&(pos_type=="cls-sep"),bar_center+3*bar_height))

for (plot_cue_type in c("context","verb")) {
d.zindiv %>%
  filter(cue_type==plot_cue_type) %>%
  group_by(head_id, layer_id, pos_type) %>%
  tidyboot_mean(effect_ave, nboot = 10) %>%
  ggplot(aes(x = as.factor(layer_id), y = empirical_stat, color = pos_type, group = pos_type, fill = pos_type)) +
    geom_hline(yintercept=0) +
    geom_line(size=0.8,position = position_dodge(width = 0.3)) +
    geom_errorbar(aes(ymin=ci_lower, ymax=ci_upper), width=0.5,size=0.5,linetype='solid',position = position_dodge(width = 0.3)) +
    scale_color_manual(values=c("#E69F00","#D55E00","#56B4E9","#009E73","#000000","#0072B2","#CC79A7")) +
    #"#000000" "#E69F00" "#56B4E9" "#009E73" "#F0E442" "#0072B2" "#D55E00" "#CC79A7"
    facet_wrap( ~ head_id) +
    theme_few() +
    labs(x = 'Layer', y ='Effect') +
    theme(aspect.ratio = 1,legend.position = 'top', legend.title = element_blank(), 
          axis.text.x=element_text(size=7),axis.text.y=element_text(size=10), axis.title=element_text(size=16),
          strip.text=element_text(size=10), legend.text=element_text(size=16)) +
    #geom_line(data=t.vals%>%filter(cue_type==plot_cue_type),
    #          aes(x=layer_id, y=y)) +
    geom_tile(data=t.vals.zrep%>%filter(cue_type==plot_cue_type),
              aes(x=layer_id, y=y),height=0.1,width=1) +
    scale_fill_manual(values=c("#E69F00","#D55E00","#56B4E9","#009E73","#000000","#0072B2","#CC79A7")) +
ggsave(paste('zrep_all_',plot_cue_type,'_p_',p_threshold,'.pdf',sep=""), units = 'in', width = 16, height = 16)
}
```

```{r}
for (plot_cue_type in c("context")) {
#for (plot_head_id in c(8,10,11,15,19,21,26,44,45,48,50,51,53)) {
for (plot_head_id in c(16,23,28,46,50)) {
  d.zindiv %>%
    filter(cue_type==plot_cue_type) %>%
    filter(head_id==plot_head_id) %>%
    filter(pos_type %in% c('context','verb','options','masks','rest')) %>%
    mutate(pos_type=factor(pos_type,levels=c('context','verb','options','masks','rest'))) %>%
    group_by(pos_type, layer_id) %>%
    #summarize(effect_ave = mean(effect_ave)) %>%
    tidyboot_mean(effect_ave, nboot = 1000) %>%
    ggplot(aes(x = as.factor(layer_id), y = empirical_stat, color = pos_type, group = pos_type)) +
      geom_hline(yintercept=0) +
      geom_line(size=1.2,position = position_dodge(width = 0.3)) +
      geom_errorbar(aes(ymin=ci_lower, ymax=ci_upper), width=0.8,size=0.8,linetype='solid',position = position_dodge(width = 0.3)) +
      theme_few() +
      scale_color_manual(values=c("#E69F00","#D55E00","#56B4E9","#009E73","#000000")) +
      #"#000000" "#E69F00" "#56B4E9" "#009E73" "#F0E442" "#0072B2" "#D55E00" "#CC79A7"
      labs(x = 'Layer', y ='Effect') +
      guides(color=guide_legend(ncol=2)) +
      theme(aspect.ratio = 1,legend.position = 'top', legend.title = element_blank(),
            axis.text.x=element_text(size=10),axis.text.y=element_text(size=14), axis.title=element_text(size=18),
            strip.text=element_text(size=16), legend.text=element_text(size=16)) +
  ggsave(paste('headwise/zrep/zrep_head_',plot_head_id,'_',plot_cue_type,'.pdf',sep=""), units = 'in', width = 3, height = 4)
}}
```

```{r}
for (plot_cue_type in c("context","verb")) {
  d.zindiv %>%
    filter(cue_type==plot_cue_type) %>%
    group_by(layer_id, head_id, pos_type) %>%
    summarize(p.val = t.test(effect_ave)$p.value,
              t.val = t.test(effect_ave)$statistic) %>%
    mutate(p.log=(-log10(p.val))) %>%
    mutate(t.bool=t.val>0) %>%
    group_by(head_id,pos_type) %>%
    slice_max(p.log) %>%
    #mutate(p.log=p.log*t.bool) %>%
    ggplot(aes(x = as.factor(head_id), y = p.log, color = t.bool)) +
      {if(plot_cue_type=="context")geom_hline(yintercept = 8, linetype="dotted")}+
      {if(plot_cue_type=="verb")geom_hline(yintercept = 24, linetype="dotted")} +
      geom_point(show.legend = FALSE) +
      theme_few() +
      labs(x = 'Head', y ='-log p',parse=TRUE) +
      #scale_color_manual(values=c("gray","black")) +
      facet_wrap( ~ pos_type, scales="free_x",ncol=1) +
      theme(aspect.ratio = 1/12,legend.position = 'top', legend.title = element_blank(),
            panel.border = element_blank(),axis.line = element_line(colour = "black"),
            axis.text.x=element_text(size=7),axis.text.y=element_text(size=10), axis.title=element_text(size=16),
            strip.text=element_text(size=10), legend.text=element_text(size=16))+
  ggsave(paste('zrep_all_pval_',plot_cue_type,'.pdf',sep=""), units = 'in', width = 8, height = 8)
}
```

```{r}
d.zindiv %>%
  filter(pos_type %in% c("context","verb","options","masks","rest")) %>%
  group_by(cue_type, layer_id, head_id, pos_type) %>%
  mutate(p.val = t.test(effect_ave)$p.value,
         t.val = t.test(effect_ave)$statistic) %>%
  mutate(p.log=(-log10(p.val))) %>%
  #mutate(t.bool=t.val>0) %>%
  group_by(cue_type, head_id, pos_type) %>%
  slice_max(t.val) %>%
  tidyboot_mean(effect_ave,nboot=10) %>%
  select(cue_type,head_id,pos_type,empirical_stat,ci_lower,ci_upper) %>%
  pivot_wider(names_from=cue_type,values_from=c("empirical_stat","ci_lower","ci_upper")) %>%
  mutate(effect_context=empirical_stat_context,effect_verb=empirical_stat_verb) %>%
  ggplot(aes(x = effect_verb, y = effect_context)) +
    geom_point(show.legend = FALSE) +
    theme_few() +
    facet_wrap(~ pos_type, scales="free") +
    geom_errorbarh(aes(xmin=ci_lower_verb, xmax=ci_upper_verb))+
    geom_errorbar(aes(ymin=ci_lower_context, ymax=ci_upper_context)) +
  ggsave('zrep_all_scatter_effect.pdf', units = 'in', width = 9, height = 6)
```

```{r}
d.zindiv %>%
  filter(pos_type %in% c("context","verb","options","masks","rest")) %>%
  group_by(cue_type, layer_id, head_id, pos_type) %>%
  summarize(p.val = t.test(effect_ave)$p.value,
            t.val = t.test(effect_ave)$statistic) %>%
  mutate(p.log=(-log10(p.val))) %>%
  #mutate(t.bool=t.val>0) %>%
  group_by(cue_type, head_id, pos_type) %>%
  slice_max(t.val) %>%
  select(cue_type,head_id,pos_type,p.log) %>%
  pivot_wider(names_from=cue_type,values_from=p.log) %>%
  mutate(logp_context=context,logp_verb=verb) %>%
  ggplot(aes(x = logp_verb, y = logp_context)) +
    geom_point(show.legend = FALSE) +
    theme_few() +
    facet_wrap(~ pos_type, scales="free") +
  ggsave('zrep_all_scatter_pval.pdf', units = 'in', width = 9, height = 6)
```

```{r}
calc_rank_diff <- function(data){
  data_new <- data %>%
    group_by(cue_type, layer_id, head_id, pos_type) %>%
    summarize(p.val = t.test(effect_ave)$p.value,
              t.val = t.test(effect_ave)$statistic) %>%
    group_by(cue_type, head_id, pos_type) %>%
    slice_max(t.val) %>%
    group_by(cue_type, pos_type) %>%
    mutate(rank = (min_rank(desc(t.val)))) %>%
    select(cue_type,head_id,pos_type,rank) %>%
    pivot_wider(names_from=cue_type,values_from=c("rank")) %>%
    mutate(rank_diff=context-verb)
}
```

```{r}
resample_data <- function(data){
  data_new <- bind_rows(data %>% 
                          filter(cue_type=="context") %>% 
                          group_by(layer_id, head_id, pos_type) %>%
                          slice_sample(n=63,replace=T),
                        data %>% 
                          filter(cue_type=="verb") %>% 
                          group_by(layer_id, head_id, pos_type) %>%
                          slice_sample(n=177,replace=T))
}
```

```{r}
d.rank <- data.frame()
for (boot_id in 1:100) {
  d.rank <- bind_rows(d.rank,
                      d.zindiv %>%
                        filter(pos_type %in% c("context","verb","options","masks","rest")) %>%
                        resample_data %>%
                        calc_rank_diff %>%
                        mutate(boot_id=boot_id))
}
d.rank %>% write_csv("rank_diff_zindiv.csv")
```

```{r}
d.rank <- read_csv("rank_diff_zindiv.csv")
d.rank %>%
  group_by(pos_type,head_id) %>%
  summarize(rank_diff_mean=mean(rank_diff),rank_diff_sd=sd(rank_diff)) %>%
  mutate(color="0") %>%
  mutate(color = replace(color,rank_diff_mean-1.96*rank_diff_sd>0,"1")) %>%
  mutate(color = replace(color,rank_diff_mean+1.96*rank_diff_sd<0,"-1")) %>%
  ggplot(aes(x=as.factor(head_id),y=rank_diff_mean,color=color)) +
    geom_point() +
    geom_hline(yintercept = 0, linetype="dotted") +
    geom_errorbar(aes(ymin=rank_diff_mean-1.96*rank_diff_sd, ymax=rank_diff_mean+1.96*rank_diff_sd),
                  width=0.8,size=0.8,linetype='solid') +
    scale_color_manual(values=c("#E69F00","#000000","#56B4E9")) +
    theme_few() +
    facet_wrap(~ pos_type, scales="free", ncol = 1) +
  ggsave('zrep_all_rank_diff.pdf', units = 'in', width = 12, height = 6)
```

```{r}
d.zindiv %>%
  filter(pos_type %in% c("context","verb","options","masks","rest")) %>%
  group_by(cue_type, layer_id, head_id, pos_type) %>%
  summarize(p.val = t.test(effect_ave)$p.value,
            t.val = t.test(effect_ave)$statistic) %>%
  group_by(cue_type, head_id, pos_type) %>%
  slice_max(t.val) %>%
  group_by(cue_type, pos_type) %>%
  mutate(rank = (min_rank(desc(t.val)))) %>%
  select(cue_type,head_id,pos_type,rank) %>%
  pivot_wider(names_from=cue_type,values_from=c("rank")) %>%
  mutate(rank_diff=context-verb)
```

```{r}
d.zindiv %>%
    filter(cue_type=="context") %>%
    group_by(layer_id, head_id, pos_type) %>%
    summarize(p.val = t.test(effect_ave)$p.value,
              t.val = t.test(effect_ave)$statistic,
              effect_ave = mean(effect_ave)) %>%
    mutate(p.log=(-log10(p.val))) %>%
    group_by(head_id,pos_type) %>%
    slice_max(p.log) %>%
    mutate(cut_off=-log10(0.001/12/64/7/2)) %>%
    filter(p.log>cut_off) %>%
    filter(t.val > 0) %>%
    arrange(head_id)
    #pull(head_id) %>% unique()
    #pull(pos_type) %>% unique()
    #filter(pos_type=="cls-sep")
```

grid with heads as columns and layers as rows with heads marked by whether they are causally implicated for verb, context, or both.

```{r}
tvals.raw <- d.zindiv %>%
    group_by(layer_id, cue_type, head_id, pos_type) %>%
    summarize(p.val = t.test(effect_ave)$p.value,
              t.val = t.test(effect_ave)$statistic) 

tvals.raw %>%
  mutate(p.log=(-log10(p.val))) %>%
  mutate(cut_off=-log10(0.01/64/12)) %>%
  filter(p.log > cut_off) %>%
  group_by(layer_id, head_id, pos_type) %>%
  select(layer_id,head_id,pos_type,p.val,cue_type) %>%
  pivot_wider(names_from = c('cue_type'), values_from = c('p.val')) %>%
  mutate(combination = case_when(is.na(verb) && !is.na(context)  ~ 'context_only',
                                    !is.na(verb) && is.na(context) ~ 'verb_only',
                                    !is.na(verb) && !is.na(context) ~ 'both',
                                    TRUE ~ 'neither')) %>%
  mutate(strength = min(-log10(max(verb, context, na.rm = T)) / 5, 1)) %>%
  filter(combination != 'verb_only') %>%
  filter(!(pos_type %in% c('period', 'cls-sep', 'context', 'verb'))) %>%
  #mutate(head_id = fct_reorder(factor(head_id), strength, .desc = T)) %>%
  ggplot(aes(x = layer_id, y = head_id, fill = combination, color = combination, alpha = strength)) +
    geom_tile() +
    facet_grid( ~ pos_type) +
    #scale_x_reverse(limits = c(12, 0.5)) +
    scale_fill_colorblind() +
    scale_color_colorblind() +
    theme_few() 

```

# 1.4.2 Attention/Q&K

```{r}
d.attqnk %>% pull(cue_type) %>% unique()
d.attqnk %>% pull(pos_type) %>% unique()
```

```{r}
p_threshold <- 0.001
d.attqnk %>%
  group_by(cue_type, layer_id, head_id, pos_type) %>%
  summarize(p.val = t.test(effect_ave)$p.value,
            t.val = t.test(effect_ave)$statistic) %>%
  mutate(p.log=(-log10(p.val))) %>%
  mutate(cut_off=-log10(p_threshold/12/64/7/2)) %>%
  filter(p.log>cut_off) %>%
  filter(t.val>0) %>%
  pull(pos_type) %>% unique()
  #filter(cue_type=='context') %>%
  #filter(pos_type=='rest-masks')
```

```{r}
p_threshold <- 0.001
bar_center <- 1.5
bar_height <- 0.1
t.vals.attqnk <- d.attqnk %>%
  mutate(pos_type=factor(pos_type,levels=c("attention","options-masks","masks-options",
                                           "rest-options","rest-masks","options-rest",
                                           "masks-rest","context-rest","verb-rest"))) %>%
  group_by(cue_type, layer_id, head_id, pos_type) %>%
  summarize(p.val = t.test(effect_ave)$p.value,
            t.val = t.test(effect_ave)$statistic) %>%
  mutate(p.log=(-log10(p.val))) %>%
  mutate(cut_off=-log10(p_threshold/12/64/7/2)) %>%
  mutate(y = NA) %>%
  mutate(y = replace(y,(p.log>cut_off)&(t.val>0)&(pos_type=="attention"),bar_center-4*bar_height)) %>%
  mutate(y = replace(y,(p.log>cut_off)&(t.val>0)&(pos_type=="options-masks"),bar_center-3*bar_height)) %>%
  mutate(y = replace(y,(p.log>cut_off)&(t.val>0)&(pos_type=="masks-options"),bar_center-2*bar_height)) %>%
  mutate(y = replace(y,(p.log>cut_off)&(t.val>0)&(pos_type=="rest-options"),bar_center-bar_height)) %>%
  mutate(y = replace(y,(p.log>cut_off)&(t.val>0)&(pos_type=="rest-masks"),bar_center)) %>%
  mutate(y = replace(y,(p.log>cut_off)&(t.val>0)&(pos_type=="options-rest"),bar_center+bar_height)) %>%
  mutate(y = replace(y,(p.log>cut_off)&(t.val>0)&(pos_type=="masks-rest"),bar_center+2*bar_height)) %>%
  mutate(y = replace(y,(p.log>cut_off)&(t.val>0)&(pos_type=="context-rest"),bar_center+3*bar_height)) %>%
  mutate(y = replace(y,(p.log>cut_off)&(t.val>0)&(pos_type=="verb-rest"),bar_center+4*bar_height))

for (plot_cue_type in c("context","verb")) {
d.attqnk %>%
  filter(cue_type==plot_cue_type) %>%
  mutate(pos_type=factor(pos_type,levels=c("attention","options-masks","masks-options",
                                           "rest-options","rest-masks","options-rest",
                                           "masks-rest","context-rest","verb-rest"))) %>%
  group_by(head_id, layer_id, pos_type) %>%
  tidyboot_mean(effect_ave, nboot = 10) %>%
  ggplot(aes(x = as.factor(layer_id), y = empirical_stat, color = pos_type, group = pos_type, fill = pos_type)) +
    geom_hline(yintercept=0) +
    geom_line(size=0.8,position = position_dodge(width = 0.3)) +
    geom_errorbar(aes(ymin=ci_lower, ymax=ci_upper), width=0.5,size=0.5,linetype='solid',position = position_dodge(width = 0.3)) +
    scale_color_manual(values=c("#000000","#E69F00","#56B4E9","#009E73","#F0E442","#0072B2","#D55E00","#CC79A7","#808080")) +
    #"#000000" "#E69F00" "#56B4E9" "#009E73" "#F0E442" "#0072B2" "#D55E00" "#CC79A7"
    facet_wrap( ~ head_id) +
    theme_few() +
    labs(x = 'Layer', y ='Effect') +
    theme(aspect.ratio = 1,legend.position = 'top', legend.title = element_blank(), 
          axis.text.x=element_text(size=7),axis.text.y=element_text(size=10), axis.title=element_text(size=16),
          strip.text=element_text(size=10), legend.text=element_text(size=16)) +
    #geom_line(data=t.vals%>%filter(cue_type==plot_cue_type),
    #          aes(x=layer_id, y=y)) +
    geom_tile(data=t.vals.attqnk%>%filter(cue_type==plot_cue_type),
              aes(x=layer_id, y=y),height=bar_height/2,width=1) +
    scale_fill_manual(values=c("#000000","#E69F00","#56B4E9","#009E73","#F0E442","#0072B2","#D55E00","#CC79A7","#808080")) +
ggsave(paste('attqnk_all_',plot_cue_type,'_p_',p_threshold,'.pdf',sep=""), units = 'in', width = 16, height = 16)
}
```

```{r}
for (plot_cue_type in c("context","verb")) {
d.attqnk %>%
  filter(cue_type==plot_cue_type) %>%
  group_by(head_id, layer_id, pos_type) %>%
  tidyboot_mean(effect_ave, nboot = 10) %>%
  ggplot(aes(x = as.factor(layer_id), y = empirical_stat, color = pos_type, group = pos_type, linetype = pos_type)) +
    geom_hline(yintercept=0) +
    geom_line(size=0.8,position = position_dodge(width = 0.3)) +
    geom_errorbar(aes(ymin=ci_lower, ymax=ci_upper), width=0.5,size=0.5,linetype='solid',position = position_dodge(width = 0.3)) +
    scale_color_manual(values=c("#000000","#E69F00","#56B4E9","#009E73","#F0E442","#0072B2","#D55E00","#CC79A7","#000000")) +
    scale_linetype_manual(values=c("dotted","solid","solid","solid","solid","solid","solid","solid","solid")) +
    #"#000000" "#E69F00" "#56B4E9" "#009E73" "#F0E442" "#0072B2" "#D55E00" "#CC79A7"
    facet_wrap( ~ head_id) +
    theme_few() +
    labs(x = 'Layer', y ='Effect') +
    theme(aspect.ratio = 1,legend.position = 'top', legend.title = element_blank(), 
          axis.text.x=element_text(size=7),axis.text.y=element_text(size=10), axis.title=element_text(size=16),
          strip.text=element_text(size=10), legend.text=element_text(size=16)) +
ggsave(paste('attqnk_all_',plot_cue_type,'.pdf',sep=""), units = 'in', width = 16, height = 16)
}
```

```{r}
for (plot_head_id in c(8,10,11,15,19,21,26,44,45,48,50,51,53)) {
for (plot_cue_type in c("context","verb")) {
d.attqnk %>%
  filter(cue_type==plot_cue_type) %>%
  filter(head_id==plot_head_id) %>%
  group_by(layer_id, pos_type) %>%
  tidyboot_mean(effect_ave, nboot = 1000) %>%
  ggplot(aes(x = as.factor(layer_id), y = empirical_stat, color = pos_type, group = pos_type)) +
    geom_hline(yintercept=0) +
    geom_line(size=1.2,position = position_dodge(width = 0.3)) +
    geom_errorbar(aes(ymin=ci_lower, ymax=ci_upper), width=0.8,size=0.8,linetype='solid',position = position_dodge(width = 0.3)) +
    scale_color_manual(values=c("#000000","#CC79A7","#0072B2")) +
    #"#000000" "#E69F00" "#56B4E9" "#009E73" "#F0E442" "#0072B2" "#D55E00" "#CC79A7"
    theme_few() +
    labs(x = 'Layer', y ='Effect') +
    guides(color=guide_legend(ncol=1)) +
    theme(aspect.ratio = 1,legend.position = 'top', legend.title = element_blank(), 
          axis.text.x=element_text(size=7),axis.text.y=element_text(size=10), axis.title=element_text(size=16),
          strip.text=element_text(size=10), legend.text=element_text(size=16)) +
ggsave(paste('headwise/attqnk/attqnk_head_',plot_head_id,'_',plot_cue_type,'.pdf',sep=""), units = 'in', width = 3, height = 4)
}}
```

```{r}
for (plot_cue_type in c("context","verb")) {
  d.attqnk%>%
    filter(cue_type==plot_cue_type) %>%
    group_by(layer_id, head_id, pos_type) %>%
    summarize(p.val = t.test(effect_ave)$p.value,
              t.val = t.test(effect_ave)$statistic) %>%
    mutate(p.log=(-log10(p.val))) %>%
    mutate(t.bool=t.val>0) %>%
    group_by(head_id,pos_type) %>%
    slice_max(p.log) %>%
    #mutate(p.log=p.log*t.bool) %>%
    ggplot(aes(x = as.factor(head_id), y = p.log, color = t.bool)) +
      {if(plot_cue_type=="context")geom_hline(yintercept = 8, linetype="dotted")}+
      {if(plot_cue_type=="verb")geom_hline(yintercept = 24, linetype="dotted")} +
      geom_point(show.legend = FALSE) +
      theme_few() +
      labs(x = 'Head', y ='-log p',parse=TRUE) +
      #scale_color_manual(values=c("gray","black")) +
      facet_wrap( ~ pos_type, scales="free_x",ncol=1) +
      theme(aspect.ratio = 1/20,legend.position = 'top', legend.title = element_blank(),
            panel.border = element_blank(),axis.line = element_line(colour = "black"),
            axis.text.x=element_text(size=7),axis.text.y=element_text(size=10), axis.title=element_text(size=16),
            strip.text=element_text(size=10), legend.text=element_text(size=16))+
  ggsave(paste('qnk_all_pval_',plot_cue_type,'.pdf',sep=""), units = 'in', width = 12, height = 12)
}
```

```{r}
d.attqnk %>%
  group_by(cue_type, layer_id, head_id, pos_type) %>%
  mutate(p.val = t.test(effect_ave)$p.value,
         t.val = t.test(effect_ave)$statistic) %>%
  mutate(p.log=(-log10(p.val))) %>%
  #mutate(t.bool=t.val>0) %>%
  group_by(cue_type, head_id, pos_type) %>%
  slice_max(t.val) %>%
  tidyboot_mean(effect_ave,nboot=10) %>%
  select(cue_type,head_id,pos_type,empirical_stat,ci_lower,ci_upper) %>%
  pivot_wider(names_from=cue_type,values_from=c("empirical_stat","ci_lower","ci_upper")) %>%
  mutate(effect_context=empirical_stat_context,effect_verb=empirical_stat_verb) %>%
  ggplot(aes(x = effect_verb, y = effect_context)) +
    geom_point(show.legend = FALSE) +
    theme_few() +
    facet_wrap(~ pos_type, scales="free") +
    geom_errorbarh(aes(xmin=ci_lower_verb, xmax=ci_upper_verb))+
    geom_errorbar(aes(ymin=ci_lower_context, ymax=ci_upper_context)) +
  ggsave('attqnk_all_scatter_effect.pdf', units = 'in', width = 9, height = 9)
```

```{r}
d.attqnk %>%
  group_by(cue_type, layer_id, head_id, pos_type) %>%
  summarize(p.val = t.test(effect_ave)$p.value,
            t.val = t.test(effect_ave)$statistic) %>%
  mutate(p.log=(-log10(p.val))) %>%
  #mutate(t.bool=t.val>0) %>%
  group_by(cue_type, head_id, pos_type) %>%
  slice_max(t.val) %>%
  select(cue_type,head_id,pos_type,p.log) %>%
  pivot_wider(names_from=cue_type,values_from=p.log) %>%
  mutate(logp_context=context,logp_verb=verb) %>%
  ggplot(aes(x = logp_verb, y = logp_context)) +
    geom_point(show.legend = FALSE) +
    theme_few() +
    facet_wrap(~ pos_type, scales="free") +
  ggsave('attqnk_all_scatter_pval.pdf', units = 'in', width = 9, height = 9)
```

# 1.4.3 Value

```{r}
d.val %>% pull(cue_type) %>% unique()
d.val %>% pull(pos_type) %>% unique()
```

```{r}
for (plot_cue_type in c("context","verb")) {
d.val %>%
  filter(cue_type==plot_cue_type) %>%
  group_by(head_id, layer_id, pos_type) %>%
  tidyboot_mean(effect_ave, nboot = 10) %>%
  ggplot(aes(x = as.factor(layer_id), y = empirical_stat, color = pos_type, group = pos_type)) +
    geom_hline(yintercept=0) +
    geom_line(size=0.8,position = position_dodge(width = 0.3)) +
    geom_errorbar(aes(ymin=ci_lower, ymax=ci_upper), width=0.5,size=0.5,linetype='solid',position = position_dodge(width = 0.3)) +
    scale_color_manual(values=c("#E69F00","#D55E00","#56B4E9","#009E73","#000000","#0072B2","#CC79A7")) +
    #"#000000" "#E69F00" "#56B4E9" "#009E73" "#F0E442" "#0072B2" "#D55E00" "#CC79A7"
    facet_wrap( ~ head_id) +
    theme_few() +
    labs(x = 'Layer', y ='Effect') +
    theme(aspect.ratio = 1,legend.position = 'top', legend.title = element_blank(), 
          axis.text.x=element_text(size=7),axis.text.y=element_text(size=10), axis.title=element_text(size=16),
          strip.text=element_text(size=10), legend.text=element_text(size=16)) +
ggsave(paste('value_all_',plot_cue_type,'.pdf',sep=""), units = 'in', width = 16, height = 16)
}
```

```{r}
p_threshold <- 0.01
bar_center <- 1
bar_height <- 0.1
t.vals.val <- d.val %>%
  group_by(cue_type, layer_id, head_id, pos_type) %>%
  summarize(p.val = t.test(effect_ave)$p.value,
            t.val = t.test(effect_ave)$statistic) %>%
  mutate(p.log=(-log10(p.val))) %>%
  mutate(cut_off=-log10(p_threshold/12/64/7/2)) %>%
  mutate(y = NA) %>%
  mutate(y = replace(y,(p.log>cut_off)&(t.val>0)&(pos_type=="context"),bar_center-3*bar_height)) %>%
  mutate(y = replace(y,(p.log>cut_off)&(t.val>0)&(pos_type=="verb"),bar_center-2*bar_height)) %>%
  mutate(y = replace(y,(p.log>cut_off)&(t.val>0)&(pos_type=="options"),bar_center-bar_height)) %>%
  mutate(y = replace(y,(p.log>cut_off)&(t.val>0)&(pos_type=="masks"),bar_center)) %>%
  mutate(y = replace(y,(p.log>cut_off)&(t.val>0)&(pos_type=="rest"),bar_center+bar_height)) %>%
  mutate(y = replace(y,(p.log>cut_off)&(t.val>0)&(pos_type=="period"),bar_center+2*bar_height)) %>%
  mutate(y = replace(y,(p.log>cut_off)&(t.val>0)&(pos_type=="cls-sep"),bar_center+3*bar_height))

for (plot_cue_type in c("context","verb")) {
d.val %>%
  filter(cue_type==plot_cue_type) %>%
  group_by(head_id, layer_id, pos_type) %>%
  tidyboot_mean(effect_ave, nboot = 10) %>%
  ggplot(aes(x = as.factor(layer_id), y = empirical_stat, color = pos_type, group = pos_type, fill = pos_type)) +
    geom_hline(yintercept=0) +
    geom_line(size=0.8,position = position_dodge(width = 0.3)) +
    geom_errorbar(aes(ymin=ci_lower, ymax=ci_upper), width=0.5,size=0.5,linetype='solid',position = position_dodge(width = 0.3)) +
    scale_color_manual(values=c("#E69F00","#D55E00","#56B4E9","#009E73","#000000","#0072B2","#CC79A7")) +
    #"#000000" "#E69F00" "#56B4E9" "#009E73" "#F0E442" "#0072B2" "#D55E00" "#CC79A7"
    facet_wrap( ~ head_id) +
    theme_few() +
    labs(x = 'Layer', y ='Effect') +
    theme(aspect.ratio = 1,legend.position = 'top', legend.title = element_blank(), 
          axis.text.x=element_text(size=7),axis.text.y=element_text(size=10), axis.title=element_text(size=16),
          strip.text=element_text(size=10), legend.text=element_text(size=16)) +
    #geom_line(data=t.vals%>%filter(cue_type==plot_cue_type),
    #          aes(x=layer_id, y=y)) +
    geom_tile(data=t.vals.val%>%filter(cue_type==plot_cue_type),
              aes(x=layer_id, y=y),height=bar_height/2,width=1) +
    scale_fill_manual(values=c("#E69F00","#D55E00","#56B4E9","#009E73","#000000","#0072B2","#CC79A7")) +
ggsave(paste('val_all_',plot_cue_type,'_p_',p_threshold,'.pdf',sep=""), units = 'in', width = 16, height = 16)
}
```

```{r}
for (plot_head_id in c(8,10,11,15,19,21,26,44,45,48,50,51,53)) {
for (plot_cue_type in c("context","verb")) {
d.val %>%
  filter(cue_type==plot_cue_type) %>%
  filter(head_id==plot_head_id) %>%
  group_by(pos_type, layer_id) %>%
  #summarize(effect_ave = mean(effect_ave)) %>%
  tidyboot_mean(effect_ave, nboot = 1000) %>%
  ggplot(aes(x = as.factor(layer_id), y = empirical_stat, color = pos_type, group = pos_type)) +
    geom_hline(yintercept=0) +
    geom_line(size=1.2,position = position_dodge(width = 0.3)) +
    geom_errorbar(aes(ymin=ci_lower, ymax=ci_upper), width=0.8,size=0.8,linetype='solid',position = position_dodge(width = 0.3)) +
    theme_few() +
    scale_color_manual(values=c("#E69F00","#D55E00","#56B4E9","#009E73","#000000","#0072B2","#CC79A7")) +
    #"#000000" "#E69F00" "#56B4E9" "#009E73" "#F0E442" "#0072B2" "#D55E00" "#CC79A7"
    labs(x = 'Layer', y ='Effect') +
    guides(color=guide_legend(ncol=2)) +
    theme(aspect.ratio = 1,legend.position = 'top', legend.title = element_blank(),
          axis.text.x=element_text(size=10),axis.text.y=element_text(size=14), axis.title=element_text(size=18),
          strip.text=element_text(size=16), legend.text=element_text(size=16)) +
ggsave(paste('headwise/val/val_head_',plot_head_id,'_',plot_cue_type,'.pdf',sep=""), units = 'in', width = 3, height = 4)
}}
```

```{r}
for (plot_cue_type in c("context","verb")) {
  d.val %>%
    filter(cue_type==plot_cue_type) %>%
    group_by(layer_id, head_id, pos_type) %>%
    summarize(p.val = t.test(effect_ave)$p.value,
              t.val = t.test(effect_ave)$statistic) %>%
    mutate(p.log=(-log10(p.val))) %>%
    mutate(t.bool=t.val>0) %>%
    group_by(head_id,pos_type) %>%
    slice_max(p.log) %>%
    #mutate(p.log=p.log*t.bool) %>%
    ggplot(aes(x = as.factor(head_id), y = p.log, color = t.bool)) +
      {if(plot_cue_type=="context")geom_hline(yintercept = 8, linetype="dotted")}+
      {if(plot_cue_type=="verb")geom_hline(yintercept = 24, linetype="dotted")} +
      geom_point(show.legend = FALSE) +
      theme_few() +
      labs(x = 'Head', y ='-log p',parse=TRUE) +
      #scale_color_manual(values=c("gray","black")) +
      facet_wrap( ~ pos_type, scales="free_x",ncol=1) +
      theme(aspect.ratio = 1/12,legend.position = 'top', legend.title = element_blank(),
            panel.border = element_blank(),axis.line = element_line(colour = "black"),
            axis.text.x=element_text(size=7),axis.text.y=element_text(size=10), axis.title=element_text(size=16),
            strip.text=element_text(size=10), legend.text=element_text(size=16))+
  ggsave(paste('val_all_pval_',plot_cue_type,'.pdf',sep=""), units = 'in', width = 8, height = 8)
}
```

```{r}
d.val %>%
  filter(pos_type %in% c("context","verb","options","masks","rest")) %>%
  group_by(cue_type, layer_id, head_id, pos_type) %>%
  mutate(p.val = t.test(effect_ave)$p.value,
         t.val = t.test(effect_ave)$statistic) %>%
  mutate(p.log=(-log10(p.val))) %>%
  #mutate(t.bool=t.val>0) %>%
  group_by(cue_type, head_id, pos_type) %>%
  slice_max(t.val) %>%
  tidyboot_mean(effect_ave,nboot=10) %>%
  select(cue_type,head_id,pos_type,empirical_stat,ci_lower,ci_upper) %>%
  pivot_wider(names_from=cue_type,values_from=c("empirical_stat","ci_lower","ci_upper")) %>%
  mutate(effect_context=empirical_stat_context,effect_verb=empirical_stat_verb) %>%
  ggplot(aes(x = effect_verb, y = effect_context)) +
    geom_point(show.legend = FALSE) +
    theme_few() +
    facet_wrap(~ pos_type, scales="free") +
    geom_errorbarh(aes(xmin=ci_lower_verb, xmax=ci_upper_verb))+
    geom_errorbar(aes(ymin=ci_lower_context, ymax=ci_upper_context)) +
  ggsave('value_all_scatter_effect.pdf', units = 'in', width = 9, height = 6)
```

```{r}
d.val %>%
  filter(pos_type %in% c("context","verb","options","masks","rest")) %>%
  group_by(cue_type, layer_id, head_id, pos_type) %>%
  summarize(p.val = t.test(effect_ave)$p.value,
            t.val = t.test(effect_ave)$statistic) %>%
  mutate(p.log=(-log10(p.val))) %>%
  #mutate(t.bool=t.val>0) %>%
  group_by(cue_type, head_id, pos_type) %>%
  slice_max(t.val) %>%
  select(cue_type,head_id,pos_type,p.log) %>%
  pivot_wider(names_from=cue_type,values_from=p.log) %>%
  mutate(logp_context=context,logp_verb=verb) %>%
  ggplot(aes(x = logp_verb, y = logp_context)) +
    geom_point(show.legend = FALSE) +
    theme_few() +
    facet_wrap(~ pos_type, scales="free") +
  ggsave('value_all_scatter_pval.pdf', units = 'in', width = 9, height = 6)
```